### ISSUE TITLE
callstack bei Zug anmieten

### ISSUE THREAD

**Issue by FalPos** [Reddog3CB/FS22_StartFarm#1]
Wenn man einen Hof ausgewählt hat, und sich dann einen Zug an mieten möchte erscheint ein callstack in der Log. Das gleiche passiert auf der Elmcreek. Hier sollte das Script überarbeitet und angepasst werden.  Mit Mod:
[log.txt](https://github.com/Reddog3CB/FS22_StartFarm/files/11069053/log.txt)

**Comment by FalPos** [comment]
Verwendet man diesen Mod nicht, ist die Log fehlerfrei

**Comment by Reddog3CB** [comment]
Hi, thanks for this. Which farm did you pick? The errors being thrown do not appear to be anything related to the mod which will be problematic for me to debug but I'll try.

**Comment by FalPos** [comment]
Ich habe es bei allen verfügbaren Farmen versucht und bei verschiedenen Schwierigkeitsgraden. Auch wenn laut Log der Mod nicht die Ursache zu sein scheint, so ist es so, das der Fehler nur dann kommt, wenn der Mod aktiviert ist. Er muss also ursächlich sein. 
Im übrigen scheint es auch Probleme zu geben wenn die vehicle.xml geladen wird. Da kamen ebenfalls Fehler. Vielleicht sollten Sie das nochmals prüfen.

**Comment by Reddog3CB** [comment]
Thanks. I've resolved the train issue and will get a hotfix version uploaded here later on, before getting it onto the modhub.

What error was thrown by the vehicle.xml? The default Elmcreek profile doesn't call any vehicle xml so there should be no vehicles?

**Comment by FalPos** [comment]
Ich hatte das bei meiner eigenen Map bemerkt. Da es mir zu viele Fehler warf habe ich es erstmal bei mir wieder deaktiviert. Ich müsste mir dies nochmal genauer anschauen was da für Fehler kamen.

**Comment by FalPos** [comment]
Leider erscheint nur dieser Fehler:

2023-03-26 12:33 Error: Running LUA method 'update'.
dataS/scripts/utils/VehicleLoadingUtil.lua(555) : attempt to call field 'asyncCallbackFunction' (a nil value)

Auch diesen Fehler habe ich ohne den Mod nicht. Anbei meine Log:  

[log.txt](https://github.com/Reddog3CB/FS22_StartFarm/files/11071328/log.txt)

**Comment by Reddog3CB** [comment]
yeah, thanks. I've already fixed that issue as well.
