### ISSUE TITLE
Feature: Seperate placeable.xml and items.xml per farm

### ISSUE THREAD

**Issue by Nightcloak** [Reddog3CB/FS22_StartFarm#2]
hi, would it be possible to have a seperate placeables.xml and items.xml per farm?

**Comment by Reddog3CB** [comment]
Hi, yes I suppose that would be possible. What's the items.xml for? I'm guessing my use of "item" in place of placeable probably hasn't helped matters either.

**Comment by Nightcloak** [comment]
usually for bales

**Comment by kf6shc** [comment]
i second this request. i would like to see item, vehicles, and farmlands available to pick per farm.

**Comment by Reddog3CB** [comment]
vehicles and farmlands are already definable by farm, that's the main point of the mod?

A revision to the mod is coming to allow defining items also, it's just taken some time.

**Comment by kf6shc** [comment]
> Hi, yes I suppose that would be possible. What's the items.xml for? I'm guessing my use of "item" in place of placeable probably hasn't helped matters either.

yes, this mislabel had me very confused.

**Comment by Reddog3CB** [comment]
Sorry about that. I'm working on an update which I hope to send to Giants for the weekend. Items have been included as well as placeables. Hopefully there'll be a few other surprises :)

**Comment by Reddog3CB** [comment]
Closing as fixed in latest release pending giants releasing.
